#!/bin/bash
python setup.py bdist_egg
rm $HOME/workspace/tracproject/plugins/Evidence*
mv -f ./dist/* $HOME/workspace/tracproject/plugins/
killall tracstart
killall tracd &
echo 'starting tracd' & tracstart > $HOME/workspace/tracproject/tracd_log &

